files = [".config/gh/config.yml", ".config/gh/hosts.yml"]

name = "GitHub CLI"
description = "GitHub CLI configuration"
method = "stow"
target = "~"

[validation]
".config/gh/config.yml" = { command = "uvx", args = [
  "--with",
  "pyyaml",
  "python3",
  "-c",
  "import sys; import yaml; yaml.safe_load(open(sys.argv[1]))",
] }
".config/gh/hosts.yml" = { command = "uvx", args = [
  "--with",
  "pyyaml",
  "python3",
  "-c",
  "import sys; import yaml; yaml.safe_load(open(sys.argv[1]))",
] }
