files = [".zshrc", ".zprofile"]

name = "Zsh"
description = "Zsh shell configuration"
method = "stow"
target = "~"

[validation]
".zshrc" = { command = "zsh", args = ["-n", "FILE"] }
".zprofile" = { command = "zsh", args = ["-n", "FILE"] }
