files = [
  ".config/fish/config.fish",
  ".config/fish/config.osx.fish",
  ".config/fish/config.linux.fish",
  ".config/fish/functions/*.fish",
  ".config/fish/conf.d/*.fish",
]

name = "Fish"
description = "Fish shell configuration"
method = "stow"
target = "~"

[validation]
".config/fish/config.fish" = { command = "fish", args = ["-n", "FILE"] }
".config/fish/config.osx.fish" = { command = "fish", args = ["-n", "FILE"] }
".config/fish/config.linux.fish" = { command = "packages/fish/validate-runtime", args = [] }
